### ISSUE TITLE
Only one NPC on list.

### ISSUE THREAD

**Issue by cedced** [jrbudda/CitizensUI#8]
Whenever i create an NPC with the UI i fills it in the save file and everything, but whenever i launch my server only 1 NPC is shown on the list, even tho all the  NPC are in the save file.

Any help is greatly appreciated.

Thanks

**Comment by ghost** [comment]
did you make sure to have your server stopped before you saved the file? if not then stop your server, save your file and start your server again. The server will write a citizens file on stop based on the active npcs on the running server.

**Comment by cedced** [comment]
No, i was actually gettinggetting a console error saying something like " "
" is an invalid ID or something like that

**Comment by cedced** [comment]
[WARNING] Task of 'Citizens' generated an exception
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at net.citizensnpcs.api.util.YamlStorage$YamlKey.getInt(YamlStorage.java:141)
    at net.citizensnpcs.api.util.YamlStorage$YamlKey.getInt(YamlStorage.java:131)
    at net.citizensnpcs.api.util.ItemStorage.loadItemStack(ItemStorage.java:16)
    at me.tehbeard.cititrader.StockRoomTrait.load(StockRoomTrait.java:69)
    at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:99)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:322)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:61)
    at net.citizensnpcs.Citizens$1.run(Citizens.java:232)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by puschie286** [comment]
the generated npc has the wrong syntax for the new version.
Have the same Problem, on my ticket are links to the generated files.
i would like to know if the programm projekt is updating. the last update was in april so it maybe the projekt is closed.
i would make the update for the programm if i could get the source files
